// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @example/hello-request.dogs
const encoding0_4 = c.array(c.string)

// @example/hello-request
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.text)
    c.string.preencode(state, m.from)
    c.int.preencode(state, m.age)
    state.end++ // max flag is 1 so always one byte
    encoding0_4.preencode(state, m.dogs)
  },
  encode(state, m) {
    const flags = m.happy ? 1 : 0

    c.string.encode(state, m.text)
    c.string.encode(state, m.from)
    c.int.encode(state, m.age)
    c.uint.encode(state, flags)
    encoding0_4.encode(state, m.dogs)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.int.decode(state)
    const flags = c.uint.decode(state)

    return {
      text: r0,
      from: r1,
      age: r2,
      happy: (flags & 1) !== 0,
      dogs: encoding0_4.decode(state)
    }
  }
}

// @example/hello-response
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.reply)
  },
  encode(state, m) {
    c.string.encode(state, m.reply)
  },
  decode(state) {
    const r0 = c.string.decode(state)

    return {
      reply: r0
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@example/hello-request':
      return encoding0
    case '@example/hello-response':
      return encoding1
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
