// This file is autogenerated by the hyperschema compiler
// Schema Version: 1

package schema

import (
	cenc "github.com/holepunchto/compact-encoding-golang"
)

type Encoding struct {
	uint    *cenc.Uint
	string  *cenc.String
	int     *cenc.Int
	bool    *cenc.Bool
	strings *cenc.Array[string]
}

var c = &Encoding{
	uint:    cenc.NewUint(),
	string:  cenc.NewString(),
	int:     cenc.NewInt(),
	bool:    cenc.NewBool(),
	strings: cenc.NewArray(cenc.NewString()),
}

type ExampleHelloRequest struct {
	Text  string
	From  string
	Age   int
	Happy bool
	Dogs  []string
}

func (m *ExampleHelloRequest) Preencode(state *cenc.State) {
	c.string.Preencode(state, m.Text)
	c.string.Preencode(state, m.From)
	c.int.Preencode(state, m.Age)
	c.bool.Preencode(state, m.Happy)
	c.strings.Preencode(state, m.Dogs)
}

func (m *ExampleHelloRequest) Encode(state *cenc.State) error {
	if err := c.string.Encode(state, m.Text); err != nil {
		return err
	}
	if err := c.string.Encode(state, m.From); err != nil {
		return err
	}
	if err := c.int.Encode(state, m.Age); err != nil {
		return err
	}
	if err := c.bool.Encode(state, m.Happy); err != nil {
		return err
	}
	if err := c.strings.Encode(state, m.Dogs); err != nil {
		return err
	}

	return nil
}

func (m *ExampleHelloRequest) Decode(state *cenc.State) error {
	var err error

	if m.Text, err = c.string.Decode(state); err != nil {
		return err
	}
	if m.From, err = c.string.Decode(state); err != nil {
		return err
	}
	if m.Age, err = c.int.Decode(state); err != nil {
		return err
	}
	if m.Happy, err = c.bool.Decode(state); err != nil {
		return err
	}
	if m.Dogs, err = c.strings.Decode(state); err != nil {
		return err
	}

	return nil
}

type ExampleHelloResponse struct {
	Reply string
}

func (m *ExampleHelloResponse) Preencode(state *cenc.State) {
	c.string.Preencode(state, m.Reply)
}

func (m *ExampleHelloResponse) Encode(state *cenc.State) error {
	if err := c.string.Encode(state, m.Reply); err != nil {
		return err
	}

	return nil
}

func (m *ExampleHelloResponse) Decode(state *cenc.State) error {
	var err error

	if m.Reply, err = c.string.Decode(state); err != nil {
		return err
	}

	return nil
}
